#
#  Libunwind Makefile.
#
#  $Id$
#

PKG_NAME = libunwind
SRC_DIR = libunwind

FETCH_TARFILE = $(SRC_DIR)-2017-07-19.tar.bz2

AC_CONFIG_DIR = config

# INSTALL_CMD = ./install

include ../build-utils/Makefile.inc
