#
#  Libunwind Makefile.
#
#  $Id$
#

PKG_NAME = libunwind
SRC_DIR = libunwind

PREREQS = lzma

FETCH_TARFILE = $(SRC_DIR)-2018-10-12.tar.bz2

AC_CONFIG_DIR = config

# INSTALL_CMD = ./install

include ../build-utils/Makefile.inc
