#
#  Libunwind Makefile.
#
#  $Id$
#

PKG_NAME = libunwind
SRC_DIR = libunwind-0.99

FETCH_TARFILE = $(SRC_DIR).tar.gz

AC_CONFIG_DIR = config

INSTALL_CMD = ./install

include ../build-utils/Makefile.inc

