#
#  Libdwarf Makefile.
#
#  $Id$
#

PKG_NAME = libdwarf
SRC_DIR = dwarf-20150915

PREREQS = libelf

FETCH_TARFILE = lib$(SRC_DIR).tar.gz

INSTALL_CMD = ./install

include ../build-utils/Makefile.inc

