#
#  Binutils Makefile.
#
#  $Id$
#

PKG_NAME = binutils
SRC_DIR = version-binutils-2.20.1

FETCH_TARFILE = binutils-2.20.1-hpc-r117.tar.gz

AC_CONFIG_DIR = binutils-2.20.1

BUILD_SUBDIRS = libiberty bfd opcodes intl binutils
POST_INSTALL_CMD = ./post-install

include ../build-utils/Makefile.inc
