#
#  Binutils Makefile.
#
#  $Id$
#
include ../Makefile.conf

PKG_NAME = binutils

FETCH_TARFILE = binutils-lite-2.27.tar.bz2

SRC_DIR = binutils-2.27
PATCH_DIR = patches-27
CONFIG_CMD = ./configure-27
POST_INSTALL_CMD = ./post-install-27
BUILD_SUBDIRS = intl libiberty zlib bfd opcodes

include ../build-utils/Makefile.inc
