#
#  Libelf/Elfutils Makefile.
#
#  $Id$
#

PKG_NAME = libelf
SRC_DIR = elfutils-0.167

PREREQS = zlib

FETCH_TARFILE = $(SRC_DIR).tar.bz2

AC_CONFIG_DIR = config

BUILD_SUBDIRS = libelf

include ../build-utils/Makefile.inc

