#
#  Libelf/Elfutils Makefile.
#
#  $Id$
#

PKG_NAME = libelf
SRC_DIR = elfutils-0.174

PREREQS = zlib

FETCH_TARFILE = elfutils-lite-0.174.tar.bz2

AC_CONFIG_DIR = config

BUILD_SUBDIRS = lib libelf libebl libdwelf libdwfl libdw

POST_INSTALL_CMD = ./post-install

include ../build-utils/Makefile.inc

