#
#  Libelf/Elfutils Makefile.
#
#  $Id$
#

PKG_NAME = libelf
SRC_DIR = elfutils-0.167

PREREQS = zlib

FETCH_TARFILE = elfutils-lite-0.167.tar.bz2

AC_CONFIG_DIR = config

BUILD_SUBDIRS = libelf

POST_INSTALL_CMD = ./post-install

include ../build-utils/Makefile.inc

