#!/bin/sh
#
#  Boost install
#
#  $Id$
#

PKG_NAME=boost
src=boost_1_59_0

. ../build-utils/configure.inc
pre_install
prefix="$boost_prefix"
include="$prefix/include"
stage="${ORIG_PKG_DIR}/work"

mkdir -p "$include" || die "unable to mkdir: $include"

echo "copying boost include files (quietly) ..."
cd "$src" || die "unable to cd: $src"
tar cf - boost | ( cd "$include" && tar xf - )
test $? -eq 0 || die "tar copy failed"

echo "copying boost library files ..."
cd "$stage" || die "unable to cd: $stage"
tar cf - lib | ( cd "$prefix" && tar xvf - )
test $? -eq 0 || die "tar copy failed"

post_install
