#
#  Boost Makefile
#
#  $Id$
#

PKG_NAME = boost
SRC_DIR = boost_1_59_0

FETCH_TARFILE = boost-headers_1_59_0.tar.bz2

CONFIG_CMD = true
BUILD_CMD = true
INSTALL_CMD = ./install

include ../build-utils/Makefile.inc
